name: Deploy Laravel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Backend EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BACK_IP }}
          username: ubuntu
          key: ${{ secrets.BACK_SSH_KEY }}
          script: |
            sudo bash /var/www/laravel-app/deploy.sh
